Feature/SMC-75: Develop test suites for IP3 ERC-20 token part
cripco/IP3 pull request #3
Opened 2022-05-09 18:31 UTC by marc-aurele-besner

## Notable changes:
- Add more test for failure in Hardhat, event testing, and more
- Add more complex test in Foundry

2022-05-09 20:58 UTC, kevinnguyen17 requested changes
Add additional test cases as commented.

Create a common function to generate permit signature like this example https://github.com/gluwa/Mainnet-DAO/blob/dev/test/shared/signature.js

2022-05-09 20:58 UTC, kevinnguyen17 commented on test/IP3Token.EthlessBurn.test.js
> +    describe('IP3Token - Test expecting failure Ethless Burn', async function () {
it is the failed case when the nonce was used only, try to add tests when different fee and amount

2022-05-09 20:58 UTC, kevinnguyen17 commented on test/IP3Token.EthlessReserve.test.js
> +    describe('IP3Token - Test expecting failure Ethless Reserve', async function () {
it is the failed case when the nonce was used only, try to add tests when different expiration, fee and amount + after expiration

2022-05-09 20:58 UTC, kevinnguyen17 commented on test/IP3Token.EthlessTransfer.test.js
> +    describe('IP3Token - Test expecting failure Ethless Transfer', async function () {
it is the failed case when the nonce was used only, try to add tests when different fee and amount

2022-05-10 19:35 UTC, kevinnguyen17 requested changes
The test suites are good. Besides, it is not necessary to test the failed txn due to reusing nonces.. in Foundry if you have done in Hardhat, instead you should compare the block numbers in the multiTxn scenario, we expect all these txns happen within the same block

2022-05-10 20:05 UTC, ohyung1287 approved these changes

2022-05-10 20:27 UTC, kevinnguyen17 approved these changes

2022-05-10 20:27 UTC, merged